name: release

on:
  push:
    branches:
      - '*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-20.04
    steps:
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: x86_64-unknown-linux-musl
      - name: install musl tools
        run: sudo apt install -y musl-tools
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-v3-${{ hashFiles('**/Cargo.lock', '.github/workflows/releases.yaml') }}
          restore-keys: ${{ runner.os }}-cargo-v3-
      - name: build
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: debug
        run: ls -R
      - name: version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)"
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: tag-${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: checksum
        run: sha256sum ./target/x86_64-unknown-linux-musl/release/bus > ./target/x86_64-unknown-linux-musl/release/bus.sha256sum
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-musl/release/bus
          asset_name: bus-linux
          asset_content_type: application/octet-stream
      - name: upload linux artifact checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/x86_64-unknown-linux-musl/release/bus.sha256sum
          asset_name: bus-linux.sha256sum
          asset_content_type: application/octet-stream
